apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "solar-system.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "solar.dev.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "solar-system.fullname" . }}
                port:
                  number: 80
