apiVersion: v1
kind: Service
metadata:
  name: {{ include "solar-system.fullname" . }}
  labels:
    {{- include "solar-system.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    {{- include "solar-system.selectorLabels" . | nindent 6 }}
